### ISSUE TITLE
External IMU support

### ISSUE THREAD

**Issue by Camilochiang** [hku-mars/r3live#3]
Will R3live support external IMU?

**Comment by ziv-lin** [comment]
As far as I am concerned, adding an external IMU is required for accurate extrinsic calibration between LiDAR and IMU, include calibrating both the spatial (the relative rotation and translation) and temporal (i.e. time delay) extrinsic.
Otherwise, it requires our estimator to online calibrate the extrinsic between LiDAR and IMU, which is not included in our current work (i.e. R2LIVE, R2LIVE  and etc).
