### ISSUE TITLE
Effect of time sync and publishing frequency

### ISSUE THREAD

**Issue by Camilochiang** [hku-mars/r3live#5]
Hei guys. A couple of question. 
What is the effect of time sync in your code? I have been able to run FASTLIO2 and R2live without time sync and I was asking me what would be the effect? would this mean less sharp point cloud?

Additionally, when first published FAST-LIO could calculate state estimation between 10 - 50 Hz. A posteriori FAST-LIO2 can estimate state at 10-100 Hz, but at the moment R2live do not allow to change the publishing frequency.
- Will R3live allow to change this?
- If yes, What will produce a better result (sharper point cloud /better position estimation)? having less lidar points will allow to faster calculations but is also more promp to fail no? What it should not happen as there is also the camera present...

Thanks in advance!

**Comment by ziv-lin** [comment]
1. Since the motion compensation of LiDAR point cloud rely on the measurement of IMU sensors, it requires a well spatial and temporal calibration between LiDAR and IMU.
2. For the camera sensor, we do not make any hardware synchronization between LiDAR and camera sensor, the time-offset between IMU (LiDAR built-in) is online estimated by our algorithm (both R2LIVE and our new work R3LIVE).
3. Both the publishing frequency of R2LIVE and R3LIVE are depend on the incoming sensor frequency.

**Comment by ziv-lin** [comment]
This issue is closed for no more updates.
Thanks~
