### ISSUE TITLE
建图轨迹与实际轨迹不符，建图效果混乱

### ISSUE THREAD

**Issue by ruiche01** [hku-mars/r3live#93]
我这里是使用无人机完成对苹果地的建图，前一半看着正常，后一半建图轨迹与无人机的轨迹完全不符合，建图效果并不是对的，看着就像是把后排的树建图和前排重影了，请问有人遇到过这个情况吗？
![2](https://user-images.githubusercontent.com/98201618/169433505-d9be3d46-1b04-41e4-87d3-946a8da4dc05.png)
![3](https://user-images.githubusercontent.com/98201618/169433796-c6ed2263-b1ba-485b-b384-769a2e120824.png)
![VO{VJZBLZY3@RW2GGB67~M0](https://user-images.githubusercontent.com/98201618/169433891-49556731-3ce5-43da-9d78-a4e569f784d6.png)
![1](https://user-images.githubusercontent.com/98201618/169433823-1f7acc90-861f-4607-b4bd-68c2de17f130.png)

**Comment by Camilochiang** [comment]
Yes. The problem is basically that r3live is looking for features (corners, planes, etc) to align the LiDAR data. In a outdoor repetitive scenario this is really hard and r3live fail (I have try with apples trees, tomatoes greenhouses and other crops and in all of them r3live fail) 

hopefully fast-livo should not have this problem as it use visual odometry for point cloud alignment ….
